services:
  - postgres:latest

variables:
  POSTGRES_DB: testase
  POSTGRES_USER: ase
  POSTGRES_PASSWORD: "ase"


# This test has two purposes:
#
#  * test with oldest supported numpy & scipy
#  * test with none of the optional dependencies
#
# It is assumed that other libraries which we depend
# on are not so version critical.  If they are, we
# should split this into two tests, so we have
# one test with minimal dependencies and another
# testing oldest supported versions of those libraries.
python_3_oldlibs_tests:
  image: python:3-slim
  script:
    - pip install numpy==1.14.0 scipy==0.13.3
    - pip install --no-deps .
    - ase test
